# Header
menu:
  主页: /
  归档: archives
  分类: categories
  标签云: tags
  关于我: about

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png

myduoshuo:
  enable: true  ## duoshuo.com
  short_name:  ## e.g. coney,duoshuo short name.

rss: /atom.xml
